=== NinaValkova/cleaning_service/cleaning_service.dtd
<!ELEMENT service (name, firm_name, address, phone, email, site, description, price, type_of_cleaning, date)>
<!ATTLIST service 
          id         ID      #REQUIRED
          regionRef  IDREF   #REQUIRED
          typeRef    IDREF   #REQUIRED>

<!ELEMENT name (#PCDATA)>
<!ELEMENT firm_name (#PCDATA)>
<!ELEMENT address (city, street)>
    <!ELEMENT city (#PCDATA)>
    <!ELEMENT street (#PCDATA)>
<!ELEMENT phone (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT site (#PCDATA)>
<!ELEMENT description (#PCDATA)>

<!ELEMENT price (season)>
<!ATTLIST price unit CDATA #REQUIRED>

<!ELEMENT season (winter, spring, autumn, summer)>
    <!ELEMENT winter (#PCDATA)>
    <!ELEMENT spring (#PCDATA)>
    <!ELEMENT autumn (#PCDATA)>
    <!ELEMENT summer (#PCDATA)>

<!ELEMENT type_of_cleaning (machines_description)>
<!ATTLIST type_of_cleaning machines_usage (yes|no) #REQUIRED>

<!ELEMENT machines_description (#PCDATA | machine)*>
    <!ELEMENT machine (machine_name, model, specifications, image)>
        <!ELEMENT machine_name (#PCDATA)>
        <!ELEMENT model (#PCDATA)>
        <!ELEMENT specifications (power, capacity, international_name)>
            <!ELEMENT power (#PCDATA)>
            <!ELEMENT capacity (#PCDATA)>
            <!ELEMENT international_name (#PCDATA)>
        <!ELEMENT image (#PCDATA)>

<!ELEMENT date (day, month, quarter, year)>
    <!ELEMENT day (#PCDATA)>
    <!ELEMENT month (#PCDATA)>
    <!ELEMENT quarter (#PCDATA)>
    <!ELEMENT year (#PCDATA)>

<!ELEMENT regions (region+)>
<!ELEMENT region (region_name)>
<!ATTLIST region 
          id         ID      #REQUIRED
          serviceRef IDREFS  #IMPLIED>
<!ELEMENT region_name (#PCDATA)>

<!ELEMENT service_types (type+)>
<!ELEMENT type (#PCDATA)>
<!ATTLIST type 
          id ID #REQUIRED>

=== NinaValkova/cleaning_service/cleaning_service_CS0002.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE service SYSTEM "cleaning_service.dtd">
<service id="CS0002" regionRef="SF" typeRef="general">
    <name>Детайлно основно почистване</name>
    <firm_name>Fresh Clean Service</firm_name>
    <address>
        <city>София</city>
        <street>ул. "Чавдар Мутафов"</street>
    </address>
    <phone>+359 888 654321</phone>
    <email>contact@freshclean.bg</email>
    <site>www.freshclean.bg</site>
    <description>Цялостно основно почистване със специализирани машини за подобрена ефективност и резултати.</description>
    <price unit="sq.m">
        <season>
            <winter>5.50</winter>
            <spring>6.00</spring>
            <autumn>5.80</autumn>
            <summer>6.20</summer>
        </season>
    </price>
    <type_of_cleaning machines_usage="yes">
        <machines_description>
            <machine>
                <machine_name>Прахосмукачка</machine_name>
                <model>Kärcher NT 65/2</model>
                <specifications>
                    <power>2760 W</power>
                    <capacity>65 L</capacity>
                </specifications>
                <image>images/karcher_nt65.jpg</image>
            </machine>
            <machine>
                <machine_name>Скрубер за под</machine_name>
                <model>Nilfisk SC351</model>
                <specifications>
                    <power>450 W</power>
                    <capacity>11 L</capacity>
                </specifications>
                <image>images/nilfisk_sc351.jpg</image>
            </machine>
        </machines_description>
    </type_of_cleaning>
    <date>
        <day>30</day>
        <month>03</month>
        <quarter>1</quarter>
        <year>2025</year>
    </date>
</service>

=== NinaValkova/cleaning_service/cleaning_service_CS0001.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE service SYSTEM "cleaning_service.dtd">
<service id="CS0001" regionRef="VN" typeRef="regular">
    <name>Редовно почистване</name>
    <firm_name>Clean Home Service</firm_name>
    <address>
        <city>Варна</city>
        <street>улица „Преслав”</street>
    </address>
    <phone>+359 889 123456</phone>
    <email>info@cleanhome.bg</email>
    <site>www.cleanhome.bg</site>
    <description>Професионално почистване за поддържане на хигиенична жилищна среда.</description>
    <price unit="sq.m">
        <season>
            <winter>3.80</winter>
            <spring>4.20</spring>
            <autumn>4.40</autumn>
            <summer>4.80</summer>
        </season>
    </price>
    <type_of_cleaning machines_usage="no">
        <machines_description>N/A</machines_description>
    </type_of_cleaning>
    <date>
        <day>25</day>
        <month>03</month>
        <quarter>1</quarter>
        <year>2025</year>
    </date>
</service>
